#!/usr/bin/env node
const http = require('http');
const app = require('../app');
const port = process.env.PORT || '3005';
app.set('port', port);
const server = http.createServer(app);

server.listen(port, function(){
    console.log("Search API: Listening on port: %s env: %s", port, app.get("env"));
});